# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b519e2522d1971d660cf086218a1cd35d4a72fe83047edc898fcf4cbda95bbab499ed8737aad2ccb08e5c9f3fd5e8baf2fb39ad1350cc0daaa929d866c38964

test:
  secret_key_base: abccf2787de1176e10f31053c40c58c099f269b7c06116b4361d77d95bdff7ecaa1c8616d116b9086f202b6b957145faac3513b0a12e5d230a78b363a2ad414b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
